export const APP_INIT = 'APP_INIT';
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const LOAD_STANDING = 'LOAD_STANDING';
export const LOAD_STANDING_REQUEST = 'LOAD_STANDING_REQUEST';
export const LOAD_STANDING_SUCCESS = 'LOAD_STANDING_SUCCESS';
export const LOAD_STANDING_FAILURE = 'LOAD_STANDING_FAILURE';

export const LOAD_SEASONS = 'LOAD_SEASONS';
export const LOAD_SEASONS_REQUEST = 'LOAD_SEASONS_REQUEST';
export const LOAD_SEASONS_SUCCESS = 'LOAD_SEASONS_SUCCESS';
export const LOAD_SEASONS_FAILURE = 'LOAD_SEASONS_FAILURE';

export const LOAD_LATEST_SEASONS = 'LOAD_LATEST_SEASONS';
export const LOAD_LATEST_SEASONS_REQUEST = 'LOAD_LATEST_SEASONS_REQUEST';
export const LOAD_LATEST_SEASONS_SUCCESS = 'LOAD_LATEST_SEASONS_SUCCESS';
export const LOAD_LATEST_SEASONS_FAILURE = 'LOAD_LATEST_SEASONS_FAILURE';

export const LOAD_STAGES = 'LOAD_STAGES';
export const LOAD_STAGES_REQUEST = 'LOAD_STAGES_REQUEST';
export const LOAD_STAGES_SUCCESS = 'LOAD_STAGES_SUCCESS';
export const LOAD_STAGES_FAILURE = 'LOAD_STAGES_FAILURE';

export const LOAD_FIXTURES = 'LOAD_FIXTURES';
export const LOAD_FIXTURES_REQUEST = 'LOAD_FIXTURES_REQUEST';
export const LOAD_FIXTURES_SUCCESS = 'LOAD_FIXTURES_SUCCESS';
export const LOAD_FIXTURES_FAILURE = 'LOAD_FIXTURES_FAILURE';

export const SET_PREDICTION = 'SET_PREDICTION';
export const SET_PREDICTION_REQUEST = 'SET_PREDICTION_REQUEST';
export const SET_PREDICTION_SUCCESS = 'SET_PREDICTION_SUCCESS';
export const SET_PREDICTION_FAILURE = 'SET_PREDICTION_FAILURE';

export const GET_PREDICTIONS = 'GET_PREDICTIONS';
export const GET_PREDICTIONS_REQUEST = 'GET_PREDICTIONS_REQUEST';
export const GET_PREDICTIONS_SUCCESS = 'GET_PREDICTIONS_SUCCESS';
export const GET_PREDICTIONS_FAILURE = 'GET_PREDICTIONS_FAILURE';
